# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
install:
- ./Scripts/install.sh
script:
- travis_wait ./Scripts/build.sh